clients = [
    {"nom": "AAAA", "email": "aaaaa@aaa.com", "montant_depense": 150.0},
    {"nom": "BBBA", "email": "bbbba@bbb.fr", "montant_depense": 201.0},
    {"nom": "BBBB", "email": "bbbbb@bbb.fr", "montant_depense": 202.0},
    {"nom": "BBBC", "email": "bbbbc@bbb.fr", "montant_depense": 3.0},
    {"nom": "BBBD", "email": "bbbbd@bbb.fr", "montant_depense": 204.0},
    {"nom": "BBBE", "email": "bbbbe@bbb.fr", "montant_depense": 205.0},
    {"nom": "BBBF", "email": "bbbbf@bbb.fr", "montant_depense": 100.0},
    {"nom": "BBBG", "email": "bbbbg@bbb.fr", "montant_depense": 99.0},
    {"nom": "BBBH", "email": "bbbbh@bbb.fr", "montant_depense": 8.0},
    {"nom": "BBBI", "email": "bbbbi@bbb.fr", "montant_depense": 209.0},
    {"nom": "BBBJ", "email": "bbbbj@bbb.fr", "montant_depense": 10.0},
    {"nom": "BBBK", "email": "bbbbk@bbb.fr", "montant_depense": 211.0},
    {"nom": "BBBL", "email": "bbbbl@bbb.fr", "montant_depense": 212.0},
    {"nom": "BBBM", "email": "bbbbm@bbb.fr", "montant_depense": 213.0},
    {"nom": "BBBN", "email": "bbbbn@bbb.fr", "montant_depense": 214.0},
    {"nom": "BBBO", "email": "bbbbo@bbb.fr", "montant_depense": 150.0},
    {"nom": "BBBP", "email": "bbbbp@bbb.fr", "montant_depense": 16.0},
    {"nom": "BBBQ", "email": "bbbbq@bbb.fr", "montant_depense": 217.0},
    {"nom": "BBBR", "email": "bbbbr@bbb.fr", "montant_depense": 218.0},
    {"nom": "BBBS", "email": "bbbbs@bbb.fr", "montant_depense": 219.0},
    {"nom": "BBBT", "email": "bbbbt@bbb.fr", "montant_depense": 20.0},
    {"nom": "BBBU", "email": "bbbbu@bbb.fr", "montant_depense": 221.0},
    {"nom": "BBBV", "email": "bbbbv@bbb.fr", "montant_depense": 222.0},
    {"nom": "BBBW", "email": "bbbbw@bbb.fr", "montant_depense": 223.0},
    {"nom": "BBBX", "email": "bbbbx@bbb.fr", "montant_depense": 224.0},
    {"nom": "BBBY", "email": "bbbby@bbb.fr", "montant_depense": 225.0},
    {"nom": "BBBZ", "email": "bbbbz@bbb.fr", "montant_depense": 5.0},
    {"nom": "BBA", "email": "bbba@bbb.fr", "montant_depense": 227.0},
    {"nom": "BBB", "email": "bbbb@bbb.fr", "montant_depense": 228.0},
    {"nom": "BBC", "email": "bbbc@bbb.fr", "montant_depense": 229.0},
    {"nom": "BBD", "email": "bbbd@bbb.fr", "montant_depense": 230.0},
    {"nom": "BBE", "email": "bbbe@bbb.fr", "montant_depense": 1050.0},
    {"nom": "BBF", "email": "bbbf@bbb.fr", "montant_depense": 232.0},
    {"nom": "BBG", "email": "bbbg@bbb.fr", "montant_depense": 233.0},
    {"nom": "BBH", "email": "bbbh@bbb.fr", "montant_depense": 234.0},
    {"nom": "BBI", "email": "bbbi@bbb.fr", "montant_depense": 35.0},
    {"nom": "BBJ", "email": "bbbj@bbb.fr", "montant_depense": 236.0},
    {"nom": "BBK", "email": "bbbk@bbb.fr", "montant_depense": 237.0},
    {"nom": "BBL", "email": "bbbl@bbb.fr", "montant_depense": 238.0},
    {"nom": "BBM", "email": "bbbm@bbb.fr", "montant_depense": 239.0},
    {"nom": "BBN", "email": "bbbn@bbb.fr", "montant_depense": 240.0},
    {"nom": "BBO", "email": "bbbo@bbb.fr", "montant_depense": 241.0},
    {"nom": "BBP", "email": "bbbp@bbb.fr", "montant_depense": 242.0},
    {"nom": "BBQ", "email": "bbbq@bbb.fr", "montant_depense": 243.0},
    {"nom": "BBR", "email": "bbbr@bbb.fr", "montant_depense": 244.0},
    {"nom": "BBS", "email": "bbbs@bbb.fr", "montant_depense": 800.0},
    {"nom": "BBT", "email": "bbbt@bbb.fr", "montant_depense": 246.0},
    {"nom": "BBU", "email": "bbbu@bbb.fr", "montant_depense": 47.0},
    {"nom": "BBV", "email": "bbbv@bbb.fr", "montant_depense": 248.0},
    {"nom": "BBW", "email": "bbbw@bbb.fr", "montant_depense": 249.0},
    {"nom": "", "email": "pasdenom@pasdenom.com", "montant_depense": 50.0},
    {"nom": "emailinvalide", "email": "emailinvalide.com", "montant_depense": 300.0},
    {"nom": "montantnegatif", "email": "montant@negatif.com", "montant_depense": -100.0},
    {"nom": 123, "email": "nom@invalide.com", "montant_depense": 100.0},
]

for client in clients:
    if client["montant_depense"] > 100:
        print(client['nom'], client['email'], client['montant_depense'])